using System;

namespace NSimpleQueue
{
  public class Comb {
    public static Guid NewComb() {
      var uid = Guid.NewGuid().ToByteArray();
      var binDate = BitConverter.GetBytes(DateTime.UtcNow.Ticks);
      var comb = new byte[uid.Length];
      comb[3] = uid[0];
      comb[2] = uid[1];
      comb[1] = uid[2];
      comb[0] = uid[3];
      comb[5] = uid[4];
      comb[4] = uid[5];
      comb[7] = uid[6];

      comb[6] = (byte)(0xc0 | (0xf & uid[7]));

      comb[9] = binDate[0];
      comb[8] = binDate[1];
      comb[15] = binDate[2];
      comb[14] = binDate[3];
      comb[13] = binDate[4];
      comb[12] = binDate[5];
      comb[11] = binDate[6];
      comb[10] = binDate[7];

      return new Guid(comb);
    }

    public static bool IsComb(Guid value) {
      var b = value.ToByteArray()[6];

      return (0xc0 & b) == 0xc0;
    }

    public static void ValidateComb(Guid value) {
      if (!IsComb(value))
        throw new ArgumentException("The supplied Id value was not generated by Comb.NewComb.");
    }
  }
}